import {
  User,
  Account,
  Category,
  Transaction,
  Asset,
  Liability,
  Goal,
  DashboardData,
} from '../types/index';
import {
  calculateTotalAssets,
  calculateTotalLiabilities,
  calculateNetWorth,
  calculateMonthlySpend,
  calculateMonthlyIncome,
  groupExpensesByCategory,
  getRecentTransactions,
  calculateAssetAllocation,
  getNetWorthTrend,
} from './calculations';

// Mock User
export const mockUser: User = {
  id: 'user_001',
  name: 'Mathan',
  email: 'mathan@example.com',
  baseCurrency: 'INR',
  createdAt: new Date('2023-03-01'),
  avatarInitials: 'MA',
};

// Mock Accounts
export const mockAccounts: Account[] = [
  {
    id: 'acc_001',
    userId: mockUser.id,
    name: 'HDFC Savings',
    type: 'bank',
    balance: 50000,
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'acc_002',
    userId: mockUser.id,
    name: 'Axis Credit Card',
    type: 'credit_card',
    balance: 0,
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'acc_003',
    userId: mockUser.id,
    name: 'Cash',
    type: 'cash',
    balance: 5000,
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 'cat_001',
    userId: mockUser.id,
    name: 'Grocery',
    emoji: '🛒',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'cat_002',
    userId: mockUser.id,
    name: 'Medical',
    emoji: '🏥',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'cat_003',
    userId: mockUser.id,
    name: 'Trip',
    emoji: '✈️',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'cat_004',
    userId: mockUser.id,
    name: 'Weekend',
    emoji: '🌅',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'cat_005',
    userId: mockUser.id,
    name: 'Party',
    emoji: '🎉',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Transactions (25+ across Jan, Feb, Mar 2026)
export const mockTransactions: Transaction[] = [
  // January 2026 - Income
  {
    id: 'txn_001',
    userId: mockUser.id,
    date: new Date('2026-01-01'),
    type: 'income',
    amount: 150000,
    category: 'Salary',
    categoryEmoji: '💰',
    accountName: 'HDFC Savings',
    description: 'Monthly Salary',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  // January 2026 - Expenses
  {
    id: 'txn_002',
    userId: mockUser.id,
    date: new Date('2026-01-05'),
    type: 'expense',
    amount: 1200,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Weekly groceries',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'txn_003',
    userId: mockUser.id,
    date: new Date('2026-01-08'),
    type: 'expense',
    amount: 2500,
    category: 'Trip',
    categoryEmoji: '✈️',
    accountName: 'HDFC Savings',
    description: 'Flight booking - weekend trip',
    createdAt: new Date('2026-01-08'),
    updatedAt: new Date('2026-01-08'),
  },
  {
    id: 'txn_004',
    userId: mockUser.id,
    date: new Date('2026-01-12'),
    type: 'expense',
    amount: 500,
    category: 'Medical',
    categoryEmoji: '🏥',
    accountName: 'Cash',
    description: 'Pharmacy - medicines',
    createdAt: new Date('2026-01-12'),
    updatedAt: new Date('2026-01-12'),
  },
  {
    id: 'txn_005',
    userId: mockUser.id,
    date: new Date('2026-01-15'),
    type: 'expense',
    amount: 1800,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Groceries and household items',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'txn_006',
    userId: mockUser.id,
    date: new Date('2026-01-18'),
    type: 'expense',
    amount: 3000,
    category: 'Party',
    categoryEmoji: '🎉',
    accountName: 'HDFC Savings',
    description: 'Friend\'s birthday celebration',
    createdAt: new Date('2026-01-18'),
    updatedAt: new Date('2026-01-18'),
  },
  {
    id: 'txn_007',
    userId: mockUser.id,
    date: new Date('2026-01-22'),
    type: 'expense',
    amount: 800,
    category: 'Weekend',
    categoryEmoji: '🌅',
    accountName: 'Cash',
    description: 'Weekend brunch',
    createdAt: new Date('2026-01-22'),
    updatedAt: new Date('2026-01-22'),
  },
  {
    id: 'txn_008',
    userId: mockUser.id,
    date: new Date('2026-01-25'),
    type: 'expense',
    amount: 1500,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Monthly groceries',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-25'),
  },

  // February 2026 - Income
  {
    id: 'txn_009',
    userId: mockUser.id,
    date: new Date('2026-02-01'),
    type: 'income',
    amount: 150000,
    category: 'Salary',
    categoryEmoji: '💰',
    accountName: 'HDFC Savings',
    description: 'Monthly Salary',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'txn_010',
    userId: mockUser.id,
    date: new Date('2026-02-05'),
    type: 'income',
    amount: 5000,
    category: 'Bonus',
    categoryEmoji: '🎁',
    accountName: 'HDFC Savings',
    description: 'Freelance project bonus',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
  },
  // February 2026 - Expenses
  {
    id: 'txn_011',
    userId: mockUser.id,
    date: new Date('2026-02-03'),
    type: 'expense',
    amount: 1000,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Groceries',
    createdAt: new Date('2026-02-03'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: 'txn_012',
    userId: mockUser.id,
    date: new Date('2026-02-08'),
    type: 'expense',
    amount: 350,
    category: 'Medical',
    categoryEmoji: '🏥',
    accountName: 'Cash',
    description: 'Doctor consultation',
    createdAt: new Date('2026-02-08'),
    updatedAt: new Date('2026-02-08'),
  },
  {
    id: 'txn_013',
    userId: mockUser.id,
    date: new Date('2026-02-10'),
    type: 'expense',
    amount: 4500,
    category: 'Trip',
    categoryEmoji: '✈️',
    accountName: 'HDFC Savings',
    description: 'Hotel booking - trip to Bangalore',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'txn_014',
    userId: mockUser.id,
    date: new Date('2026-02-14'),
    type: 'expense',
    amount: 2000,
    category: 'Party',
    categoryEmoji: '🎉',
    accountName: 'Cash',
    description: 'Valentine\'s dinner',
    createdAt: new Date('2026-02-14'),
    updatedAt: new Date('2026-02-14'),
  },
  {
    id: 'txn_015',
    userId: mockUser.id,
    date: new Date('2026-02-18'),
    type: 'expense',
    amount: 1200,
    category: 'Weekend',
    categoryEmoji: '🌅',
    accountName: 'HDFC Savings',
    description: 'Weekend getaway',
    createdAt: new Date('2026-02-18'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'txn_016',
    userId: mockUser.id,
    date: new Date('2026-02-22'),
    type: 'expense',
    amount: 1400,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Weekly shopping',
    createdAt: new Date('2026-02-22'),
    updatedAt: new Date('2026-02-22'),
  },
  {
    id: 'txn_017',
    userId: mockUser.id,
    date: new Date('2026-02-25'),
    type: 'expense',
    amount: 600,
    category: 'Medical',
    categoryEmoji: '🏥',
    accountName: 'Cash',
    description: 'Health supplements',
    createdAt: new Date('2026-02-25'),
    updatedAt: new Date('2026-02-25'),
  },

  // March 2026 - Income
  {
    id: 'txn_018',
    userId: mockUser.id,
    date: new Date('2026-03-01'),
    type: 'income',
    amount: 150000,
    category: 'Salary',
    categoryEmoji: '💰',
    accountName: 'HDFC Savings',
    description: 'Monthly Salary',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  // March 2026 - Expenses
  {
    id: 'txn_019',
    userId: mockUser.id,
    date: new Date('2026-03-02'),
    type: 'expense',
    amount: 2200,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Groceries and pantry items',
    createdAt: new Date('2026-03-02'),
    updatedAt: new Date('2026-03-02'),
  },
  {
    id: 'txn_020',
    userId: mockUser.id,
    date: new Date('2026-03-05'),
    type: 'expense',
    amount: 3500,
    category: 'Trip',
    categoryEmoji: '✈️',
    accountName: 'HDFC Savings',
    description: 'Car rental for trip',
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'txn_021',
    userId: mockUser.id,
    date: new Date('2026-03-08'),
    type: 'expense',
    amount: 800,
    category: 'Medical',
    categoryEmoji: '🏥',
    accountName: 'Cash',
    description: 'Dental checkup and cleaning',
    createdAt: new Date('2026-03-08'),
    updatedAt: new Date('2026-03-08'),
  },
  {
    id: 'txn_022',
    userId: mockUser.id,
    date: new Date('2026-03-12'),
    type: 'expense',
    amount: 1100,
    category: 'Weekend',
    categoryEmoji: '🌅',
    accountName: 'HDFC Savings',
    description: 'Weekend picnic',
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
  },
  {
    id: 'txn_023',
    userId: mockUser.id,
    date: new Date('2026-03-15'),
    type: 'expense',
    amount: 2800,
    category: 'Party',
    categoryEmoji: '🎉',
    accountName: 'HDFC Savings',
    description: 'House party and dinner',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'txn_024',
    userId: mockUser.id,
    date: new Date('2026-03-18'),
    type: 'expense',
    amount: 900,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'Cash',
    description: 'Weekly groceries',
    createdAt: new Date('2026-03-18'),
    updatedAt: new Date('2026-03-18'),
  },
  {
    id: 'txn_025',
    userId: mockUser.id,
    date: new Date('2026-03-20'),
    type: 'expense',
    amount: 1600,
    category: 'Grocery',
    categoryEmoji: '🛒',
    accountName: 'HDFC Savings',
    description: 'Bulk groceries purchase',
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'txn_026',
    userId: mockUser.id,
    date: new Date('2026-03-22'),
    type: 'expense',
    amount: 450,
    category: 'Medical',
    categoryEmoji: '🏥',
    accountName: 'Cash',
    description: 'Pharmacy supplies',
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
  },
];

// Mock Assets
export const mockAssets: Asset[] = [
  // Stocks
  {
    id: 'ast_001',
    userId: mockUser.id,
    name: 'Reliance',
    type: 'stocks',
    currentValue: 25000,
    units: 10,
    exchange: 'NSE',
    notes: 'Long-term holding',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'ast_002',
    userId: mockUser.id,
    name: 'TCS',
    type: 'stocks',
    currentValue: 20000,
    units: 5,
    exchange: 'NSE',
    notes: 'Tech sector investment',
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'ast_003',
    userId: mockUser.id,
    name: 'Infosys',
    type: 'stocks',
    currentValue: 14400,
    units: 8,
    exchange: 'BSE',
    notes: 'Dividend paying stock',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Mutual Funds
  {
    id: 'ast_004',
    userId: mockUser.id,
    name: 'SIP Direct Fund',
    type: 'mutual_funds',
    currentValue: 50000,
    subType: 'direct',
    notes: 'Regular SIP investment',
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'ast_005',
    userId: mockUser.id,
    name: 'Growth Mutual Fund',
    type: 'mutual_funds',
    currentValue: 30000,
    subType: 'growth',
    notes: 'High growth fund',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Gold
  {
    id: 'ast_006',
    userId: mockUser.id,
    name: 'Physical Gold',
    type: 'gold',
    currentValue: 300000,
    units: 50,
    notes: '50 grams at ₹6000/gram',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Bank FD and Cash
  {
    id: 'ast_007',
    userId: mockUser.id,
    name: 'Bank Savings',
    type: 'bank_fd',
    currentValue: 100000,
    notes: 'High-yield savings account',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'ast_008',
    userId: mockUser.id,
    name: 'Fixed Deposit',
    type: 'bank_fd',
    currentValue: 75000,
    notes: '2-year FD at 6.5% interest',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Crypto
  {
    id: 'ast_009',
    userId: mockUser.id,
    name: 'Bitcoin Holdings',
    type: 'crypto',
    currentValue: 100000,
    notes: 'Long-term crypto investment',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Cash
  {
    id: 'ast_010',
    userId: mockUser.id,
    name: 'Cash in Hand',
    type: 'cash',
    currentValue: 5000,
    notes: 'Emergency cash',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-03-20'),
  },
];

// Mock Liabilities
export const mockLiabilities: Liability[] = [
  {
    id: 'liab_001',
    userId: mockUser.id,
    name: 'Personal Loan',
    type: 'personal_loan',
    totalAmount: 500000,
    outstandingAmount: 400000,
    notes: 'Home renovation loan, 5 year tenure',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'liab_002',
    userId: mockUser.id,
    name: 'Credit Card Due',
    type: 'credit_card',
    totalAmount: 10000,
    outstandingAmount: 8000,
    notes: 'Axis Bank credit card - due next month',
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'liab_003',
    userId: mockUser.id,
    name: "Friend's Loan",
    type: 'informal_loan',
    totalAmount: 50000,
    outstandingAmount: 50000,
    notes: 'Loan from friend Rajesh',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-03-20'),
  },
];

// Mock Goals
export const mockGoals: Goal[] = [
  {
    id: 'goal_001',
    userId: mockUser.id,
    name: 'Emergency Fund',
    targetAmount: 300000,
    targetDate: new Date('2026-12-31'),
    currentAmount: 180000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'goal_002',
    userId: mockUser.id,
    name: 'Europe Trip',
    targetAmount: 500000,
    targetDate: new Date('2026-09-30'),
    currentAmount: 200000,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'goal_003',
    userId: mockUser.id,
    name: 'MacBook Pro',
    targetAmount: 150000,
    targetDate: new Date('2026-08-31'),
    currentAmount: 120000,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'goal_004',
    userId: mockUser.id,
    name: 'House Down Payment',
    targetAmount: 2000000,
    targetDate: new Date('2028-12-31'),
    currentAmount: 500000,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-03-20'),
  },
];

/**
 * Generate comprehensive dashboard data from mock data
 */
export function generateMockDashboardData(): DashboardData {
  const totalAssets = calculateTotalAssets(mockAssets);
  const totalLiabilities = calculateTotalLiabilities(mockLiabilities);
  const netWorth = calculateNetWorth(totalAssets, totalLiabilities);

  // Current month is March 2026
  const monthlySpend = calculateMonthlySpend(mockTransactions, 3, 2026);
  const monthlyIncome = calculateMonthlyIncome(mockTransactions, 3, 2026);

  const expensesByCategory = groupExpensesByCategory(mockTransactions);
  const recentTransactions = getRecentTransactions(mockTransactions, 10);
  const assetAllocation = calculateAssetAllocation(mockAssets);
  const netWorthTrend = getNetWorthTrend(mockTransactions, mockAssets, '3m');

  return {
    totalAssets,
    totalLiabilities,
    netWorth,
    monthlySpend,
    monthlyIncome,
    expensesByCategory,
    netWorthTrend,
    recentTransactions,
    assetAllocation,
  };
}

/**
 * Get all mock data in the same shape returned by the app data layer.
 */
export function getMockData() {
  return {
    user: mockUser,
    accounts: mockAccounts,
    categories: mockCategories,
    transactions: mockTransactions,
    assets: mockAssets,
    liabilities: mockLiabilities,
    goals: mockGoals,
    dashboard: generateMockDashboardData(),
  };
}

/**
 * Export for use in individual modules
 */
export default getMockData;
